# Generated by Django 3.2.6 on 2021-08-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='foto',
            field=models.ImageField(default=6, upload_to='', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
